config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :orders
  resources :sessions
  resources :complains

  # Main page
  root 'home#index'

  #get 'orders', to: 'orders#index', as: 'orders'
  get 'home', to: 'home#index', as: 'home'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/complain.rb
class Complain < ApplicationRecord
  belongs_to :locale, required: false
end

app/models/locale.rb
class Locale < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :locale
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  def digest(string)
     cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
     BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/complains_controller.rb
class ComplainsController < ApplicationController

  def new
    @complain = Complain.new
  end

  def create
    @complain = Complain.new(allowed_params)


    # todo: refactor to a class/method
    @complain.maybe_fraud = false;
    # Check if the complained shipping zipcode are present in any order 
    @order = Order.find_by shipping_zipcode:  @complain.shipping_zipcode

    if @order.nil?
      @complain.maybe_fraud = true
    end

    # todo: refactor to a class/method
    # Check if the complained order number exists
    @order = Order.find_by order_number: @complain.order

    if @order.nil?
      @complain.maybe_fraud = true
    end

    # Get address from shopping_zipcode
    @address = get_address

    # Get where the guy made the shit
    @complain.ip_address = request.remote_ip
    geodata = get_ip_locale @complain.ip_address

    # Create Locale
    if not geodata.nil?
      @locale = Locale.new
      @locale.latitude = geodata['latitude'].to_f
      @locale.longitude = geodata['longitude'].to_f
      @locale.country = geodata['country_name']
      @locale.city = geodata['city']
      @locale.save
      @complain.locale_id = @locale.id

      # Check if the complain are from Brazil
     if geodata['country_name'] != 'Brazil'
        complain.maybe_fraud = true
     end
    end


    # Saving all stuff
    if @complain.save
      redirect_to root_url, notice: 'Agradeço e espero podermos ajudar!'
    else
      redirect_to root_path
    end
  end

  def show
    @complain = Complain.find(params[:id])
    @address = get_address
  end

  def index
    @complains = Complain.all
  end

  private

  def allowed_params
    params.require(:complain).permit!
  end

  def get_address
    @response = Faraday.get 'http://viacep.com.br/ws/'+ @complain.shipping_zipcode.to_s + '/json'

    if @response.status == 400
      @address = 'cep inválido'
      @complain.maybe_fraud = true
    else
      if @response.status == 200
        obj =  JSON.parse(@response.body)
        if obj['erro']
          @address = 'cep inexistente'
          @complain.maybe_fraud = true
        else
          @address = obj['logradouro'] + ' ' + obj['bairro'] + ' '+ obj['complemento']
        end
      end
    end

    @address
  end

  def get_ip_locale ip
    @ip_response = Faraday.get 'https://api.ipgeolocation.io/ipgeo?apiKey=90609d68cf15435ba67e68818df5eb9e&ip='+ip.to_s

    if @ip_response.status == 400
      @ip_address = 'cannot get info'
    else
      if @ip_response.status == 200
        obj = JSON.parse(@ip_response.body)
      end
    end

    obj
  end
end 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(allowed_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thanks Signing up!'
    else
      render :new
    end
  end

  private
  def allowed_params
    params.require(:user).permit(:email,:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

private

def logged_in?
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

# todo: logged_as_admin?
end

app/helpers/complains_helper.rb
module ComplainsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/complains/index.html.erb
<!-- todo: Pagination and get the reason of suspect of Fraud -->

<h1> Complains </h1>

<% if @complains.each do |complain| %>
  <div>
    <h3>
       Pedido: <%= link_to complain.order, complain %>
     <% if complain.maybe_fraud == "1" then %>
       <i class="glyphicon glyphicon-alert" style="color:red"></i>
     <% else %>
       <i class="glyphicon glyphicon-ok" style="color:green"></i>
     <% end %>
    </h3>
    <p>Cep do Endereço de Entrega: <%= complain.shipping_zipcode %> </p>
    <% end.empty? %>
    <p> Who haa! Não há reclamações na base! </p>
  </div>
<% end %>

app/views/complains/new.html.erb
<small> <%= @ip_address %> </small>
<h1> Atendimento ao Público </h1>

<h2> Por favor informe o seu problema </h2>
<%= form_for @complain do |f| %>
  <p>
    <%= f.label :name %> <br />
    <%= f.text_field :name, placeholder: 'Name', :required => true %> <br />
  </p>
  <p>
    <%= f.label :email %> <br />
    <%= f.text_field :email, type: 'email', placeholder: 'Email', :required => true  %> <br />
  </p>
  <p>
    <%= f.label :phone %> <br />
    <%= f.text_field :phone, :required => true  %> <br />
  </p>
  <p>
    <%= f.label :order %> <br />
    <%= f.text_field :order, maxlength: 8, :required => true  %> <br />
  </p>
  <p>
    <%= f.label :shipping_zipcode %> <br />
    <%= f.text_field :shipping_zipcode, maxlength: 8, :required => true  %> <br />
  </p>
  <p>
    <%= f.label :description %> <br />
    <%= f.text_area :description, :required => true  %> <br />
  </p>

  <p>
  <%= f.submit "Enviar" %>
  </p>
<% end %>

<%= link_to "Back", root_path %>

app/views/complains/show.html.erb
<h1>Reclamação: (Pedido#<%= @complain.order %>)</h1>

<h2> Informações da reclamação </h2>
<p> Nome Reclamante: <%= @complain.name %> </p>
<p> Email: <%= @complain.email %> </p>
<p> Telefone: <%= @complain.phone %> </p>
<p> Cep Entrega: <%= @complain.shipping_zipcode %> </p>
<p> Endereço: <%= @address %> </p>
<p> Descrição do ocorrido: <%= @complain.description %> </p>
<p> Localização: <br />

<blockquote>
  <% if @complain.locale %>
  <p> País: <%= @complain.locale.country %> </p>
  <p> Cidade: <%= @complain.locale.city %> </p>
  <p>
    <small> Latitude/Longitude:
    <%= @complain.locale.latitude %> /
    <%= @complain.locale.longitude %>
    </small>
  </p>
  <% else %>
    <p>Geo localização não encontrada! </p>
  <% end %>
</blockquote>

<%= link_to "Back", complains_path %>

app/views/home/index.html.erb
<h1> Reclame Aí! </h1>
<div class="row">
Looks like a airplane, without wings. Doc, I'm from the future. I came here in a time machine that you invented. Now, I need your help to get back to the year 1985. Wow, you must be rich. Now Biff, don't con me. Hey, not too early I sleep in on Saturday. Oh, McFly, your shoe's untied. Don't be so gullible, McFly. You got the place fixed up nice, McFly. I have you're car towed all the way to your house and all you've got for me is light beer. What are you looking at, butthead. Say hi to your mom for me.
</div>

<hr />

<h2> Sobre </h2>
<div class="row">
    <div class="col-sm-8">
      <p>That's a great idea. I'd love to park. Really. The flux capacitor. Alright, I'm ready. Whoa, wait a minute, Doc, are you telling me that my mother has got the hots for me?</p>

      <p> Einstein, hey Einstein, where's the Doc, boy, huh? Doc Of course I do. Just a second, let's see if I could find it. I swiped it from the old lady's liquor cabinet. Wrecked? When did this happen and- Hey, McFly, I thought I told you never to come in here. Well it's gonna cost you. How much money you got on you?</p>

      <p> Hey man, look at Marvin's hand. He can't play with his hands like that, and we can't play without him. Oh. It's cold, damn cold. Ha, ha, ha, Einstein, you little devil. Einstein's clock is exactly one minute behind mine, it's still ticking. It's uh, the other end of town, a block past Maple. Well, it will just happen. Like the way I met your father.</p>
    </div>

    <div class="col-sm-4">
      <%= image_tag("teste.jpg") %>
    </div>
</div>

<hr />


<div class="row">
  <p>C'mon, more, dammit. Jeez. Holy shit. Let's see if you bastards can do ninety. What? Yeah. Get out of town, I didn't know you did anything creative. Ah, let me read some. Um, well it's a delorean, right?</p>
</div>

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <%= link_to "Reclame Aí", new_complain_path, :class => "button btn btn-primary btn-lg" %>
  </div>
  <div class="col-md-4"></div>
</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom ">
  <span class="text-muted"> 
    This page is licensed to the public under a Creative Commons Attribution 4.0 license - ReclameAí 2019 - cc
  </span>
</footer>

app/views/layouts/_navigation.html.erb
<nav class = "navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <p class="navbar-brand">Reclame Aí!</p>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to 'Home', home_path %></li>
      <% if logged_in? %>
      <li><%= link_to "Complains", complains_path %></li>
      <li><%= link_to 'Orders', orders_path %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if !logged_in? %>
      <li>
        <%= link_to signup_path do %>
          <span class="glyphicon glyphicon-user"></span>Sign-up
        <% end %>
      </li>
      <li>
        <%= link_to login_path do %>
          <span class="glyphicon glyphicon-login-in"></span>Log-in
        <% end %>
      </li>
      <% end %>
      <% if logged_in? %>
      <li>
        <%= link_to logout_path do %>
          <span class="glyphicon glyphicon-login-out"></span>Log-out
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReclameAi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/navigation' %>

  <div class="container">
  <body>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
  </body>
  </div>

  <%= render 'layouts/footer' %>
</html>

app/views/orders/index.html.erb
<!-- 
  # todo: - sistema de roles para que seja exibido apenas os pedidos de um usuario especifico
  #       - ... e caso seja um user admin, exibir tudo mesmo
--> 

<h1> Orders </h1>

<% @orders.each do |order| %>
  id: <%= order.id %>
  <h2>Number: <%= link_to order.order_number, order %></h2>
  <small> <%= order.created_at.strftime("%b %d, %Y") %></small>

  <p>Endereço Entrega: <%= order.shipping_address %></p>
  <p>Cep Entrega: <%= order.shipping_zipcode %></p>
  <p>Descrição: <%= order.description %><p>

  <hr />
<% end %>

app/views/orders/show.html.erb
<h1> Pedido: <%= @order.order_number %> </h1>

<h2> # Mapa da localização do pedido </h2>
<p>
  <small>Latitude: <%= @order.locale.latitude %> |
    Longitude: <%= @order.locale.longitude %>
  </small>
</p>
<%= link_to "Back", orders_path %>

app/views/users/new.html.erb
<h1> Sign Up Man! </h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>